-- AlterTable
ALTER TABLE `restaurant` MODIFY `RSTR_RDNMADR` VARCHAR(191) NULL,
    MODIFY `RSTR_TELNO` VARCHAR(191) NULL,
    MODIFY `BSNS_STATM_BZCND_NM` VARCHAR(191) NULL,
    MODIFY `BSNS_LCNC_NM` VARCHAR(191) NULL,
    MODIFY `RSTR_INTRCN_CONT` VARCHAR(191) NULL,
    MODIFY `RSTR_LNNO_ADRES` VARCHAR(191) NULL;
